phaseChildrenBP = {
  "phase1": [
    {
      name: "Exploratorium",
      assetDirectory: "bp/exploratorium",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "How do you take training and turn it on its head? BPNYC created the concept of the Exploratorium – a training environment like no other. Our Exploratorium provides a provocative self-led learning experience where participants visit exhibits, interact with displays, immerse themselves in relevant, emotional stories and meet and speak with subject matter experts. Participants spend time where they need the most help, learning in a style that suits them.",
      video: "output.mp4",
      label: "label_Exploratorium.png",
    },
    {
      name: "Immersive Experiences",
      assetDirectory: "bp/immersive",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "We invite participants to step inside environments that are intimate, exciting, true-to- life, and positive for the learning process. When learners are immersed in the content, they are true participants. After touching, feeling, and seeing, they come out on the other side knowing the training content in a visceral way. Plus, it all lingers long after the event is over.",
      video: "output.mp4",
      label: "label_Immersiveenv.png",
    },
    {
      name: "Content Development",
      assetDirectory: "bp/content",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "We believe <b>adults love to learn, but hate to be told</b>; BLUEPRINT NYC learning strategists, backed by a full team of talented writers, eagle eye editors, graphic wizards, video peeps, and crazed coders create content that educates, engages, and inspires learners on their journey.",
      video: "output.mp4",
      label: "label_Contentdev.png",
    },
    {
      name: "Storytelling",
      assetDirectory: "bp/storytelling",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: 'Storytelling is one of the hottest buzzwords in sales training today. But at Blueprint NYC, we’re not selling hype. We’re offering real skill development that everyone at any level can benefit from – representatives, managers, sales leaders, brand managers, and more. Our 2-hour workshop begins with the essentials of a compelling story, but we diverge from other coaching on the market with an added focus to make the story authentically your own.<br><br>“If you slide a person into an FMRI machine that watches the brain while the brain watches a story, you’ll find something interesting—the brain doesn’t look like a spectator, it looks more like a participant in the action.” <br>—Jonathan Gottschall',
      video: "output.mp4",
      label: "label_Storytelling.png",
    },
    {
      name: "Video",
      assetDirectory: "bp/video",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "Since we opened, BlueprintNYC has been producing custom video experiences – Documentary, Animation, and Stylized Concept videos –for a variety of industries. Our videos provide a great emotional impact, humor, and educational content. Integrating these videos into greater training experiences and communications campaigns is a specialty of ours.",
      video: "output.mp4",
      label: "label_Video.png",
    },
    {
      name: "Conventions",
      assetDirectory: "bp/conventions",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "From inception and installation, to staffing and show days, through dismantling, clean up and storage; BLUEPRINTNYC has proven Exhibit Hall Domination. We bring insight and ideation to shape strategy, and couple creativity with daring for the execution. Above all else, we are not just building a flashy booth, we are telling the client story.",
      video: "output.mp4",
      label: "label_Conventions.png",
    },
  ],
  "phase2": [
    {
      name: "Broadcast Training",
      assetDirectory: "bp/broadcast",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "How can you consistently engage over 2,700+ people at the same time in over 40 locations? Use our app to stream live video to attendees all across the country, including Puerto Rico and Hawaii. Onsite training can be expensive, and isn’t needed for every meeting or every message. BlueprintNYC can connect your teams virtually so they can experience the learning, teambuilding, engagement, and inspiration of a company-wide meeting in realtime, without the heavy cost of airfare and lodging.",
      video: "output.mp4",
      label: "label_Broadcast.png",
    },
    {
      name: "District / Regional Meetings",
      assetDirectory: "bp/district",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC can help you pre-package your training, messaging, and teambuilding content for use at the local level. Use our app to help district leaders serve videos, documents, and interactive games to their small circle of direct reports. The same content can experienced across the nation or around the world, led by local leaders, without the heavy cost of airfare and lodging.",
      video: "output.mp4",
      label: "label_Districtreg.png",
    },
    {
      name: "Custom Training Apps",
      assetDirectory: "bp/custom",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC has mastered the art of integrating effective, purposeful technology into the training room. iPad or touchscreen-driven training provides an opportunity for learners to get hands on and digest complex concepts in a fun and different way, and maybe experience a little friendly competition to boot. With all of our digital training, BlueprintNYC develops powerful analytics so we can evaluate the growth, gaps, and trends in your learners.",
      video: "output.mp4",
      label: "label_Customtrain.png",
    },
    {
      name: "Strategic Communications",
      assetDirectory: "bp/strategic",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "With the BLUEPRINTNYC Communication Strategy Service, you get a strategic program to ensure continuity and follow-through. Your message stays firmly top of mind, extending the life of your meeting and maximizing results. We mix it up with communications that bring leadership, patient and customer voices to life through videos and written and animated graphic communications. And we bring the field’s voice into the conversation through selfie videos, photo competitions, and other two-way conversation pieces.",
      video: "output.mp4",
      label: "label_Strategiccom.png",
    },

  ],
  "phase3": [
    {
      name: "Training Analytics",
      assetDirectory: "bp/training",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC provides actionable analytics baked into our training methodologies, and finds areas of opportunity by analyzing these results in real time. We understands the benefits of gathering immediate results through digital assessment and seize opportunities for adaptive instruction, so you can close the understanding gap before the moment passes.",
      video: "output.mp4",
      label: "label_Traininganal.png",
    },
    {
      name: "Certification",
      assetDirectory: "bp/certification",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "The reason we engage in training is to get results. At BlueprintNYC we we monitor learning with efficient and sophisticated certification methods. By conducting certification digitally, your facilitators and your leadership team have an instant high-level view of the process, including real time analytics across a number of dimensions.",
      video: "output.mp4",
      label: "label_Certification-.png",
    },
    {
      name: "Custom Event App",
      assetDirectory: "bp/custom_event",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "We couldn't find a meeting app that did everything we wanted, so we decided to build one ourselves. Meeting Architect, BlueprintNYC's custom meeting and event app, engages your audience with interactive learning, communication campaigns, and presentations, as well as personalized meeting information and agendas for each attendee.",
      video: "output.mp4",
      label: "label_Customeve.png",
    },
    {
      name: "Gamification",
      assetDirectory: "bp/gamification",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "Gamification can be built into onsite training, digital training, even communication campaigns to engage your learners at the highest level. It goes beyond friendly competition. It’s about developing content and delivery systems that balance challenge with delight. Individual results can be tracked and reported – and, if appropriate, applied toward a meeting-wide competition with winners. The buzz created is undeniable.",
      video: "output.mp4",
      label: "label_Gamification.png",
    },
  ]
}
