phaseChildren = {
  phase1: [
    {
      name: "MEDI7836",
      subtitle: "Anti-IL-13 mAb-YTE",
      assetDirectory: "moleculeImages/MEDI7836",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>MEDI7836 is an investigational Anti-IL-13 monoclonal antibody</div></li><li><div>Interleukin 13 (IL-13) is a cytokine that is hypothesized to play a key role in the pathogenesis of asthma and is predominantly produced by T helper 2 cells, although various other immune cells are also capable of its release in the lung tissue, including eosinophils, natural killer cells, mast cells, basophils, and injured epithelial cells.</div></li><li><div>MEDI7836 is currently in Phase I clinical development for asthma</div></li>",
      video: "output.mp4",
      label: "label_MEDI7836.png",
      large: true,
      asthma: true,
    },

    {
      name: "AZD8871",
      subtitle: "MABA",
      assetDirectory: "moleculeImages/AZD8871",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD8871 is an investigational muscarinic antagonist/beta<sub>2</sub> agonist (MABA).</div></li><li><div>MABAs are bi-functional, single-molecule agents which combine both β<sub>2</sub>-agonism and muscarinic antagonism</div></li><li><div>AZD8871 is currently in Phase I clinical development for COPD</div></li>",
      video: "output.mp4",
      label: "label_AZD8871.png",
      small: true,
      copd: true
    },
    {
      name: "AZD7986",
      subtitle: "DPP-1 inhibitor",
      assetDirectory: "moleculeImages/AZD7986",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD7986 is an investigational DPP-1 (dipeptidyl peptidase-1) inhibitor</div></li><li><div>DPP-1 (also known as cathepsin C) is hypothesized to act as a physiological activator or neutrophil-derived serine proteases.  DPP-1 may therefore play a role in neutrophil-dominated inflammatory diseases</div></li><li><div>AZD7986 is currently in Phase I clinical development for COPD</div></li>",
      video: "output.mp4",
      label: "label_AZD7986.png",
      small: true,
      copd: true,
    },

    {
      name: "AZD8999",
      subtitle: "MABA",
      assetDirectory: "moleculeImages/AZD8999",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD8999 is an investigational muscarinic antagonist/beta<sub>2</sub> agonist (MABA)</div></li><li><div>MABAs are bi-functional, single-molecule agents which combine both β<sub>2</sub>-agonism and muscarinic antagonism</div></li><li><div>AZD8999 is currently in Phase I clinical development for COPD</div></li>",
      video: "output.mp4",
      label: "label_AZD8999.png",
      small: true,
      copd: true,
    },
    {
      name: "AZD1419",
      subtitle: "TLR9 agonist",
      assetDirectory: "moleculeImages/AZD1419",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD1419 is an investigational inhaled Toll-like receptor 9 (TLR9) agonist</div></li><li><div>Stimulation of TLR9 triggers dendritic cells to secrete Type 1 interferons, suppressing the Th2 cascade and inhibiting cytokine secretion from Th2 cells, such as IL-13, IL-4, IL-5</div></li><li><div>AZD1419 is currently in Phase I clinical development for asthma</div></li>",
      video: "output.mp4",
      label: "label_AZD1419.png",
      small: true,
      asthma: true,
    },
  ],
  phase2: [
    {
      //name: "MEDI9929/AMG157",
      name: "Tezepelumab",
      subtitle: "Anti-TSLP mAb",
      assetDirectory: "moleculeImages/Tezep",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>Tezepelumab (MEDI9929/AMG 157) is an investigational fully human anti-thymic stromal lymphopoietin (anti-TSLP) monoclonal antibody designed to block TSLP from interaction with the TSLP receptor</div></li><li><div>TSLP is an epithelial cell‐derived cytokine that is produced in response to proinflammatory stimuli and drives allergic inflammatory responses through its effects on multiple cell types involved in atopic asthma</div></li><li><div>Tezepelumab is currently in Phase II clinical development for asthma</div></li>",
      video: "output.mp4",
      label: "label_Tezepelumab.png",
      large: true,
      asthma: true,
    },
    {
      name: "AZD9412",
      subtitle: "Inhaled interferon beta-1a",
      assetDirectory: "moleculeImages/AZD9412",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD9412 is an investigational inhaled interferon beta-1a </div></li><li><div>Interferon beta activates downstream kinases (JAK) and transcription factors (STAT) to activate anti-viral and pro-apoptotic genes, thereby limiting viral replication.</div></li><li><div>AZD9412 is currently in Phase II clinical development for asthma and COPD</div></li>",
      video: "output.mp4",
      label: "label_AZD9412.png",
      large: true,
      asthma: true,
      copd: true,
    },
    {
      name: "PT010",
      subtitle: "LAMA/LABA/ICS",
      assetDirectory: "moleculeImages/PT010",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>PT010 is an investigational fixed‐dose, triple combination therapy containing glycopyrrolate (LAMA), formoterol fumarate (LABA), and budesonide (ICS) using co‐suspension technology, and delivered in a pressurized metered dose inhaler (pMDI)</div></li><li><div>Antagonism of the muscarinic receptor restores smooth muscle dilation by inhibiting intracellular effects of inositol triphosphate</div></li><li><div>β<sub>2</sub> adrenergic receptor agonists activate adenylate cyclase, resulting a cAMP-mediated cascade, the activation of PKA, and airway smooth muscle relaxation</div></li><li><div>Activation of the glucocorticoid receptor upregulates the expression of anti-inflammatory gene transcription in the nucleus and suppresses pro-inflammatory gene transcription</li></div><li><div>PT010 is currently in Phase III clinical development for COPD and is also in Phase II clinical development for asthma</li></div>",
      video: "output.mp4",
      label: "label_PT010-06.png",
      small: true,
      asthma: true,
      copd: false
    },
    {
      name: "Abediterol",
      subtitle: "LABA",
      assetDirectory: "moleculeImages/Abed",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>Abediterol (AZD0548) is an investigational long‐acting beta<sub>2</sub>‐agonist (LABA)</div></li><li><div>Activation of the β<sub>2</sub> receptor relaxes airway smooth muscle and may also inhibit mediator release from mast cells, prevent plasma exudation, and inhibit activation of sensory nerves</div></li><li><div>Abediterol is currently in Phase II clinical development for asthma and COPD</div></li>",
      video: "output.mp4",
      label: "label_Abediterol.png",
      small: true,
      asthma: true,
      copd: true,
    },
    {
      name: "AZD7624",
      subtitle: "Inhaled p38 inhibitor",
      assetDirectory: "moleculeImages/AZD7624",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD7624 is an investigational inhaled p38 inhibitor</div></li><li><div>Expression of p38 is upregulated in COPD. Additionally, phospho-p38+ alveolar macrophages have been shown to be increased in COPD.  Phosphorylation of p38 leads to the activation of downstream kinases and transcription factors mediating inflammatory responses</div></li><li><div>AZD7624 is currently in Phase II clinical development for COPD</div></li>",
      video: "output.mp4",
      label: "label_AZD7624.png",
      small: true,
      copd: true,
    },
    {
      name: "AZD7594",
      subtitle: "Inhaled SGRM",
      assetDirectory: "moleculeImages/AZD7594",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>AZD7594 is an investigational inhaled, non-steroidal selective glucocorticoid receptor modulator (SGRM)</div></li><li><div>Binding and subsequent activation of the glucocorticoid receptor (GR) leads to translocation to the nucleus and results in  upregulation of anti-inflammatory gene transcription and suppression of pro-inflammatory gene transcription</div></li><li><div>Inhaled SGRMs are designed to bind with high affinity to GR over other hormone receptors, such as the androgen receptor & mineralocorticoid receptor</div></li><li><div>AZD7594 is currently in Phase II clinical development for asthma and for COPD</div></li>",
      video: "output.mp4",
      label: "label_AZD7594.png",
      small: true,
      asthma: true,
      copd: true,
    },
  ],
  phase3: [
    {
      name: "PT010",
      subtitle: "LAMA/LABA/ICS",
      assetDirectory: "moleculeImages/PT010",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>PT010 is an investigational fixed‐dose, triple combination therapy containing glycopyrrolate (LAMA), formoterol fumarate (LABA), and budesonide (ICS) using co‐suspension technology, and delivered in a pressurized metered dose inhaler (pMDI)</div></li><li><div>Antagonism of the muscarinic receptor restores smooth muscle dilation by inhibiting intracellular effects of inositol triphosphate</div></li><li><div>β<sub>2</sub> adrenergic receptor agonists activate adenylate cyclase, resulting a cAMP-mediated cascade, the activation of PKA, and airway smooth muscle relaxation</div></li><li><div>Activation of the glucocorticoid receptor upregulates the expression of anti-inflammatory gene transcription in the nucleus and suppresses pro-inflammatory gene transcription</div></li><li><div>PT010 is currently in Phase III clinical development for COPD and is also in Phase II clinical development for asthma</div></li>",
      video: "output.mp4",
      label: "label_PT010-13.png",
      small: true,
      copd: true,
      asthma: false,
    },
    {
      name: "Benralizumab",
      subtitle: "Anti-IL-5Rα mAb",
      assetDirectory: "moleculeImages/Benra",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>Benralizumab (MEDI‐563) is an investigational humanized anti-IL-5 receptor alpha (anti-IL-5Rα) monoclonal antibody</div></li><li><div>Benralizumab is designed to bind to the alpha chain of the interleukin-5 receptor (IL-5R), enabling effector cells to induce the apoptosis of and thereby depleting eosinophils via antibody-dependent cell-mediated cytotoxicity (ADCC)</div></li><li><div>The constant region (Fc) of benralizumab is afucosylated, leading to increased affinity for the Fc gamma receptor 3 (FcγRIIIa) found on the surface of effector cells, such as natural killer cells</div></li><li><div>Benralizumab is currently in Phase III clinical development for severe asthma and COPD</div></li>",
      video: "output.mp4",
      label: "label_Benralizumab.png",
      large: true,
      copd: true,
      asthma: true,
    },
    /*
    {
      name: "PT003",
      subtitle: "LAMA/LABA",
      assetDirectory: "moleculeImages/PT003",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>PT003 is an investigational fixed‐dose, dual bronchodilator containing glycopyrrolate (LAMA) and formoterol fumarate (LABA) using co‐suspension technology, and delivered in a pressurized metered dose inhaled (pMDI)</div></li><li><div>Antagonism of the muscarinic receptor restores smooth muscle dilation by inhibiting the intracellular effects of inositol triphosphate</div></li><li><div>β<sub>2</sub> adrenergic receptor agonists activate adenylate cyclase, resulting a cAMP-mediated cascade, the activation of PKA, and airway smooth muscle relaxation</div></li><li><div>PT003 is Phase III clinical development for COPD</div></li>",
      video: "output.mp4",
      label: "label_pt0032.png",
      small: true,
      copd: true,
    },
    */
    {
      name: "Tralokinumab",
      subtitle: "anti-IL-13 mAb",
      assetDirectory: "moleculeImages/Tralok",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>Tralokinumab (CAT‐354) is an investigational human monoclonal antibody designed to neutralize IL-13</div></li><li><div>Interleukin 13 (IL-13) is a cytokine that is hypothesized to play a key role in the pathogenesis of asthma and is predominantly produced by T helper 2 cells, although various other immune cells are also capable of its release in the lung tissue, including eosinophils, natural killer cells, mast cells, basophils, and injured epithelial cells.</div></li><li><div>IL-13 overexpression has been associated with Th2-driven inflammation airway hyperresponsiveness and mucus hypersecretion from goblet cells</div></li><li><div>Tralokinumab is currently in Phase III clinical development for severe asthma</div></li>",
      video: "output.mp4",
      label: "label_Tralokinumab.png",
      large: true,
      asthma: true,
    },
    {
      name: "Aclidinium / Formoterol",
      subtitle: "LAMA/LABA",
      assetDirectory: "moleculeImages/Aclid",
      assetsStart: 1,
      assetsEnd: 75,
      duration: 5,
      text: "<li><div>Aclidinium/formoterol is an investigational fixed dose combination of a long‐acting muscarinic antagonist (LAMA) and a long‐acting beta<sub>2</sub>‐agonist (LABA) delivered in a DPI (dry powder inhaler)</div></li><li><div>Antagonism of the muscarinic receptor restores smooth muscle dilation by inhibiting the intracellular effects of inositol triphosphate</div></li><li><div>β<sub>2</sub> adrenergic receptor agonists activate adenylate cyclase, resulting a cAMP-mediated cascade, the activation of PKA, and airway smooth muscle relaxation</div></li><li><div>Aclidinium/formoterol is currently in Phase III clinical development for COPD</div></li>",
      video: "output.mp4",
      label: "label_Aclidinium.png",
      small: true,
      copd: true,
    },
  ]
}
