phaseChildrenBP = {
  "phase1": [
    {
      name: "Exploratorium",
      assetDirectory: "bp/exploratorium",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "How do you take training and turn it on its head? BlueprintNYC created the concept of the Exploratorium – a training environment like no other. Our Exploratorium provides a provocative self-led learning experience where participants visit exhibits, interact with displays, immerse themselves in relevant, emotional stories and meet and speak with subject matter experts. Participants spend time where they need the most help, learning in a style that suits them.",
      video: "output.mp4",
      label: "label_Exploratorium.png",
    },
    {
      name: "Immersive Environment",
      assetDirectory: "bp/immersive",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "At BlueprintNYC we invite participants to step inside environments that are intimate, exciting, true-to-life, and positive for the learning process. When learners are immersed in the content, they are true participants. After engaging all five sense, they come out on the other side knowing the training content in a visceral way. Plus, it all lingers long after the event is over.",
      video: "output.mp4",
      label: "label_Immersiveenv.png",
    },
    {
      name: "Content Development",
      assetDirectory: "bp/content",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "We believe <b>adults love to learn, but hate to be told</b>; BlueprintNYC learning strategists, backed by a full team of talented writers, eagle eye editors, graphic wizards, video peeps, and crazed coders create content that educates, engages, and inspires learners on their journey.",
      video: "output.mp4",
      label: "label_Contentdev.png",
    },
    {
      name: "Storytelling",
      assetDirectory: "bp/storytelling",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: 'Storytelling is one of the hottest buzzwords in sales training today. But at BlueprintNYC, we’re not selling hype. We’re offering real skill development that everyone at any level can benefit from – representatives, managers, sales leaders, brand managers, and more. Our 2-hour workshop begins with the essentials of a compelling story, but we diverge from other coaching on the market with an added focus to make the story authentically your own.',
      video: "output.mp4",
      label: "label_Storytelling.png",
    },
    {
      name: "Video",
      assetDirectory: "bp/video",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "Since we opened, BlueprintNYC has been producing custom video experiences – Documentary, Animation, and Stylized Concept videos –for a variety of industries. Our videos provide a great emotional impact, humor, and educational content. Integrating these videos into greater training experiences and communications campaigns is a specialty of ours.",
      video: "output.mp4",
      label: "label_Video.png",
    },
    {
      name: "Conventions",
      assetDirectory: "bp/conventions",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "From inception and installation, staffing and dismantling, clean up and storage, BlueprintNYC has proven exhibit hall mastery. Ideation shapes the strategy. We couple creativity with daring for the execution. Above all else, we are not just building a flashy booth, we are telling your story.",
      video: "output.mp4",
      label: "label_Conventions.png",
    },
  ],
  "phase2": [
    {
      name: "Broadcast Training",
      assetDirectory: "bp/broadcast",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "How can you engage over 2,700 people at the same time in over 40 locations? Use our app to stream live video to attendees across the country, including Puerto Rico and Hawaii. Onsite training can be expensive, and isn’t needed for every meeting or every message. BlueprintNYC can connect your teams virtually so they can experience the learning, teambuilding, engagement, and inspiration of a company-wide meeting in real-time, without the heavy cost of airfare and lodging.",
      video: "output.mp4",
      label: "label_Broadcast.png",
    },
    {
      name: "District / Regional Meetings",
      assetDirectory: "bp/district",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC can help you pre-package your training, messaging, and teambuilding content for use at the local level. Use our app to help district leaders serve videos, documents, and interactive games to their small circle of direct reports. The same content can experienced across the nation or around the world, led by local leaders. With BlueprintNYC you can to ensure top-quality training, even on your smaller programs.",
      video: "output.mp4",
      label: "label_Districtreg.png",
    },
    {
      name: "Custom Training Apps",
      assetDirectory: "bp/custom",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC has mastered the art of integrating effective, purposeful technology into the training room. iPad or touchscreen-driven training provides an opportunity for learners to get hands on and digest complex concepts in a fun and different way, and maybe experience a little friendly competition to boot. With all of our digital training, BlueprintNYC develops powerful analytics so we can evaluate the growth, gaps, and trends in your learners.",
      video: "output.mp4",
      label: "label_Customtrain.png",
    },
    {
      name: "Strategic Communications",
      assetDirectory: "bp/strategic",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "With the BlueprintNYC Communication Strategy Service, you get a strategic program that ensures continuity and follow-through. We mix it up with communications that bring leadership, patient, and customer voices to life through videos, animations, and written communications. And it’s a two way conversation: bring the field’s voice into the conversation through selfie videos, photo competitions, and other two-way conversation pieces. Your message stays firmly top of mind, maximizing results.",
      video: "output.mp4",
      label: "label_Strategiccom.png",
    },
    {
      name: "Virtual Reality",
      assetDirectory: "bp/vr",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC can use virtual reality to give your learners, customers, and training special insight into complex concepts and stories. Whether you use high quality medical animation or documentary style 360 videos, VR can offer a new perspective and new opportunities in training.",
      video: "output.mp4",
      label: "label_vr.png",
    },

  ],
  "phase3": [
    {
      name: "Training Analytics",
      assetDirectory: "bp/training",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC provides actionable analytics baked into our training methodologies, and finds areas of opportunity by analyzing these results in real time. We understand the benefits of gathering immediate results through digital assessment and seize opportunities for adaptive instruction, so you can close the understanding gap before the moment passes.",
      video: "output.mp4",
      label: "label_Traininganal.png",
    },
    {
      name: "Certification",
      assetDirectory: "bp/certification",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "We engage in training to get results. At BlueprintNYC we we monitor learning with efficient and sophisticated certification methods. By conducting certification digitally, your facilitators and your leadership team have an instant high-level view of the process, including real time analytics across a number of dimensions.",
      video: "output.mp4",
      label: "label_Certification-.png",
    },
    {
      name: "Custom Event App",
      assetDirectory: "bp/custom_event",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "We couldn't find a meeting app that did everything we wanted, so we built our own. Meeting Architect, BlueprintNYC's custom meeting and event app, engages your audience with interactive learning, communication campaigns, and presentations, as well as personalized meeting information and agendas for each attendee.",
      video: "output.mp4",
      label: "label_Customeve.png",
    },
    {
      name: "Gamification",
      assetDirectory: "bp/gamification",
      assetsStart: 1,
      assetsEnd: 1,
      duration: 5,
      text: "BlueprintNYC has built Gamification into onsite training, digital training, even communication campaigns to engage your learners at the highest level. It goes beyond friendly competition. It’s about developing content and delivery systems that balance challenge with delight. Individual results can be tracked and reported – and, if appropriate, applied toward an event-wide competition with winners. The buzz created is undeniable.",
      video: "output.mp4",
      label: "label_Gamification.png",
    },
  ]
}
